services:
  - type: web
    name: birthday-greetings
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: birthday-uploads
      mountPath: /opt/uploads
      sizeGB: 1 